# Generated by Django 2.2 on 2021-07-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0002_auto_20210704_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
