# Generated by Django 2.2 on 2021-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0004_auto_20210705_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteredItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=27, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, max_length=189, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items_in_order',
            field=models.ManyToManyField(related_name='orders_of_items', to='imgfield_app.EnteredItem'),
        ),
        migrations.AddField(
            model_name='quote',
            name='items_in_quote',
            field=models.ManyToManyField(related_name='quotes_of_items', to='imgfield_app.EnteredItem'),
        ),
    ]
