# Generated by Django 2.2 on 2021-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0005_auto_20210705_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='ref_number',
            field=models.CharField(max_length=10),
        ),
    ]
