# Generated by Django 2.2 on 2021-07-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0006_auto_20210705_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_in_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products_in_order',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='items_in_quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='products_in_quote',
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_on_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_of_product', to='imgfield_app.Product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_product', to='imgfield_app.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_on_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_of_item', to='imgfield_app.EnteredItem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_item', to='imgfield_app.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='imgfield_app.Order')),
                ('product_on_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_product', to='imgfield_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_on_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_item', to='imgfield_app.EnteredItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='imgfield_app.Order')),
            ],
        ),
    ]
