# Generated by Django 2.2 on 2021-07-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0007_auto_20210705_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entereditem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
