# Generated by Django 2.2 on 2021-07-06 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0009_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 6, 13, 0, 44, 936329, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='zip_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_2',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
