# Generated by Django 2.2 on 2021-07-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0011_auto_20210707_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='quote',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='imgfield_app.ContactInfo'),
        ),
        migrations.AddField(
            model_name='quote',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='imgfield_app.ContactInfo'),
        ),
    ]
