# Generated by Django 2.2 on 2021-07-08 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0012_auto_20210708_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 12, 57, 412225)),
        ),
    ]
