# Generated by Django 2.2 on 2021-07-09 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0014_auto_20210708_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 20, 2, 5, 467317)),
        ),
    ]
