# Generated by Django 2.2 on 2021-07-09 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0018_auto_20210709_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entereditem',
            name='name',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 7, 5, 34, 378217)),
        ),
    ]
