# Generated by Django 2.2 on 2021-07-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgfield_app', '0025_auto_20210709_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=108)),
                ('part_number', models.CharField(blank=True, max_length=27, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_discount', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteAdminItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('combined_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_discount', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adminitem_on_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_of_adminitem', to='imgfield_app.AdminItem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_adminitem', to='imgfield_app.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAdminItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('combined_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_discount', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adminitem_on_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_adminitem', to='imgfield_app.AdminItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_adminitem', to='imgfield_app.Order')),
            ],
        ),
    ]
